### ISSUE TITLE
No route matches [GET] "/api_docs/null/debug"

### ISSUE THREAD

**Issue by ryy** [ZuzannaSt/swagger_ui_engine#42]
When I open swagger, I get an error that I can't see the image.

<img width="1013" alt="スクリーンショット 2020-06-12 16 50 24" src="https://user-images.githubusercontent.com/13917558/84478809-ded49100-accc-11ea-8c11-c2356c1e0a02.png">

```
Started GET "/api_docs/null?url=http://192.168.33.10:3000/api/swagger.yaml" for 192.168.33.1 at 2020-06-12 07:43:54 +0000
  
ActionController::RoutingError (No route matches [GET] "/api_docs/null"):
  
actionpack (5.2.4.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.3) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.3) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.3) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by akosipc** [comment]
@ryo19910801 You need to set `validator_enabled` in your SwaggerUiEngine config. I was having the same problem and this fixed it. I've included a sample config for your convenience.

```ruby
SwaggerUiEngine.configure do |config|
  config.validator_enabled = 'https://validator.swagger.io/validator'
end
```
